[package]
name = "fortress"
version = "0.0.1"
authors = ["fpgaminer"]

[dependencies]
libfortress = { path = "./libfortress" }
rustc-serialize = "0.3"
clap = "2.23"

[dependencies.gtk]
version = "0.1.2"
features = ["v3_10"]