[package]
authors = ["fpgaminer"]
name = "fortress"
version = "0.0.1"

[dependencies]
clap = "2.23"
data-encoding = "2.0.0-rc.1"

[dependencies.gtk]
features = ["v3_10"]
version = "0.1.2"

[dependencies.libfortress]
path = "./libfortress"
